import{a as P,i as n,S as v}from"./assets/vendor-BkVuWn-o.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const m=15;async function y(e,r){const s="53374689-de9604de74fdd47daed383deb";try{const a=await P.get("https://pixabay.com/api/",{params:{key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:m}});return!a.data.hits||a.data.hits.length===0?(n.info({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight",timeout:3e3}),{hits:[],totalHits:0}):{hits:a.data.hits,totalHits:a.data.totalHits}}catch{return n.error({message:"Something went wrong. Please try again later.",backgroundColor:"#ef4040",position:"topRight",timeout:4e3}),{hits:[],totalHits:0}}}const C=new v(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:500}),f=document.querySelector(".gallery"),g=document.querySelector(".load-more-wrapper .loader");function E({webformatURL:e,largeImageURL:r,tags:s,likes:a,views:t,comments:o,downloads:c}){return`     
      <li class="gallery-card">
        <a href="${r}" class="gallery-link">
          <img src="${e}" alt="${s}" loading="lazy" class="gallery-image" width="360" height="200"/>
        </a>
        <div class="gallery-stats">
          <p><strong>Likes</strong> <span class="likes">${a}</span></p>
          <p><strong>Views</strong> <span class="views">${t}</span></p>
          <p><strong>Comments</strong> <span class="comments">${o}</span></p>
          <p><strong>Downloads</strong> <span class="downloads">${c}</span></p>
        </div>
      </li>`}function h(e){return e.map(E).join("")}function b(e,r=!1){r?f.innerHTML=h(e):f.insertAdjacentHTML("beforeend",h(e)),C.refresh()}function R(){f.innerHTML=""}function w(){g&&g.classList.remove("hidden")}function L(){g&&g.classList.add("hidden")}function S(e){e.classList.remove("hidden")}function u(e){e.classList.add("hidden")}const k=document.querySelector(".form"),i=document.querySelector(".js-btn-load");let d,l,p;u(i);k.addEventListener("submit",async e=>{if(e.preventDefault(),d=new FormData(e.target).get("search-text").trim(),l=1,!d){n.warning({message:"Please, enter something!",backgroundColor:"#ef4040",position:"topRight"});return}R(),w(),u(i);try{const{hits:s,totalHits:a}=await y(d,l);await b(s,!0),p=Math.ceil(a/m),s.length===0?n.info({message:"No results found.",backgroundColor:"#ef4040",position:"topRight"}):l>=p?(u(i),n.info({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#67dadcff",position:"topRight"})):S(i)}catch{n.error({message:"Error! Please try again!",backgroundColor:"#ef4040",position:"topRight"})}finally{L()}e.target.reset()});i.addEventListener("click",async()=>{l+=1,w();try{const{hits:e}=await y(d,l);if(e.length===0||l>=p)u(i),n.info({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#67dadcff",position:"topRight"});else{await b(e,!1);const s=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch{n.error({message:"Error! Please try again!",backgroundColor:"#ef4040",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
