import{a as P,i as n,S as v}from"./assets/vendor-BkVuWn-o.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const m=15;async function y(e,a){const s="53374689-de9604de74fdd47daed383deb";try{const r=await P.get("https://pixabay.com/api/",{params:{key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:m}});return!r.data.hits||r.data.hits.length===0?(n.info({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight",timeout:3e3}),{hits:[],totalHits:0}):{hits:r.data.hits,totalHits:r.data.totalHits}}catch{return n.error({message:"Something went wrong. Please try again later.",backgroundColor:"#ef4040",position:"topRight",timeout:4e3}),{hits:[],totalHits:0}}}const k=new v(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:500}),f=document.querySelector(".gallery"),g=document.querySelector(".load-more-wrapper .loader");function C({webformatURL:e,largeImageURL:a,tags:s,likes:r,views:t,comments:o,downloads:c}){return`     
      <li class="gallery-card">
        <a href="${a}" class="gallery-link">
          <img src="${e}" alt="${s}" loading="lazy" class="gallery-image" width="360" height="200"/>
        </a>
        <div class="gallery-stats">
          <p><strong>Likes</strong> <span class="likes">${r}</span></p>
          <p><strong>Views</strong> <span class="views">${t}</span></p>
          <p><strong>Comments</strong> <span class="comments">${o}</span></p>
          <p><strong>Downloads</strong> <span class="downloads">${c}</span></p>
        </div>
      </li>`}function h(e){return e.map(C).join("")}function b(e,a=!1){a?f.innerHTML=h(e):f.insertAdjacentHTML("beforeend",h(e)),k.refresh()}function E(){f.innerHTML=""}function L(){g&&g.classList.remove("hidden")}function w(){g&&g.classList.add("hidden")}function R(e){e.classList.remove("hidden")}function u(e){e.classList.add("hidden")}const S=document.querySelector(".form"),i=document.querySelector(".js-btn-load");let d,l,p;u(i);S.addEventListener("submit",async e=>{if(e.preventDefault(),d=new FormData(e.target).get("search-text").trim(),l=1,!d){n.warning({message:"Please, enter something!",backgroundColor:"#ef4040",position:"topRight"});return}E(),L(),u(i);try{const{hits:s,totalHits:r}=await y(d,l);await b(s,!0),p=Math.ceil(r/m),s.length===0?n.info({message:"No results found.",backgroundColor:"#ef4040",position:"topRight"}):l>=p?(u(i),n.info({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#67dadcff",position:"topRight"})):R(i)}catch{n.error({message:"Error! Please try again!",backgroundColor:"#ef4040",position:"topRight"})}finally{w()}e.target.reset()});i.addEventListener("click",async()=>{l+=1,L();try{const{hits:e}=await y(d,l);await b(e,!1),(e.length===0||l>=p)&&(u(i),n.info({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#67dadcff",position:"topRight"}))}catch{n.error({message:"Error! Please try again!",backgroundColor:"#ef4040",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
